apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: angular-frontend-project
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: angular-frontend-project
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-angular
    - name: gitops_ssh_secret
      value: git-ssh
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: ssh://git@github.com/jkhan24558/angular-frontend-project.git
      ref:
        branch: main