apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dallecool
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "false"
    app.kubernetes.io/part-of: dallecool
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_ssh_secret
      value: git-ssh
  source:
    git:
      url: ssh://git@github.com/jkhan24558/dallecool.git
      ref:
        branch: main
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  - name: openai
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: openai-claim
